color: teal
fieldLayouts:
  8bb2d266-de84-4e99-9831-8be6d70a0108:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-25T19:54:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1900abeb-2b54-48e8-90a9-828bbd537aaa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-25T19:55:47+00:00'
            elementCondition: null
            fieldUid: 9797be5d-2efb-4770-9533-2bbd715a0c7b # Block Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa20ff7-d58d-4ee3-b904-91ed47febf72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-25T19:55:47+00:00'
            elementCondition: null
            fieldUid: 06f7c30f-645c-489e-8904-daafa63d6d8d # Block Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4504ca7e-1d08-4980-b771-dc9afda1c8c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f2ca27cb-f4b9-44d5-addb-648a1be5da0a
        userCondition: null
handle: galleryBlock
hasTitleField: false
icon: rectangle-history
name: 'Gallery Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{blockAnchor}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
