headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  alignment:
    options:
      - left
      - right
toolbar:
  - heading
  - createEntry
  - '|'
  - alignment
  - bold
  - italic
  - link
  - anchor
  - pageBreak
  - '|'
  - blockQuote
  - bulletedList
  - numberedList
  - outdent
  - indent
  - insertImage
  - mediaEmbed
