altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2c6499d2-1113-4ef4-897b-19f8f9e80492:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-25T18:45:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e49ae68f-f505-4ecc-b101-be6211dc251d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41cd36d4-1c7f-4f23-a88e-4eaf577dc16f
        userCondition: null
fs: localAssets
handle: seoImages
name: 'SEO Images'
sortOrder: 2
subpath: seo
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
