columnSuffix: null
handle: blockContent
instructions: null
name: 'Block Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 8f8318c7-5311-4b13-9a2c-ba5e1ad60ea1 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
