columnSuffix: null
handle: blockAnchor
instructions: '[options] If set, the user will be able to travel to this block with #{your-text-here}'
name: 'Block Anchor'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
