dateModified: 1727193166
email:
  fromEmail: email@clarknelson.com
  fromName: 'Craft Dev'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4ce5ba56-132c-4aca-9085-8d7f1568d039: 'Craft Dev' # Craft Dev
    44839323-84f3-45bd-84de-324e58547d82: 'Craft Dev' # Craft Dev
system:
  edition: solo
  live: true
  name: 'Craft Dev'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
