defaultPlacement: end
enableVersioning: true
entryTypes:
  - d82a1dd6-dc01-462b-883a-8ef07ed50b95 # Home
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  44839323-84f3-45bd-84de-324e58547d82: # Craft Dev
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
